### ISSUE TITLE
Does not run since update

### ISSUE THREAD

**Issue by bellegarde-c** [flathub/de.schmidhuberj.Flare#1]
(flare:2): GLib-GIO-ERROR **: 00:16:13.880: Settings schema 'de.schmidhuberj.Flare' is not installed

**Comment by bellegarde-c** [comment]
Ah, you already fixed it in next release, sorry for noise ;)

**Comment by Schmiddiii** [comment]
Yes, someone already notified me about this. I am currently in the process of releasing the new version, but this will still take a few hours until it finished building and Flathub publishes it.
