### ISSUE TITLE
Libsecret missing

### ISSUE THREAD

**Issue by firefoxlover** [flathub/de.schmidhuberj.Flare#23]
Nice app!

In the flatpak libsecret is not bundled, I guess this is Gnome keyring. I dont know if you have to install that on the system for it to work.

Weird thing is, I have libsecret installed.

Fedora 38 KDE Kinoite

libsecret-0.20.5-3.fc38.x86_64

Version 0.8.0

**Comment by Schmiddiii** [comment]
Sorry, I seemed to have missed this issue. Yes, GNOME keyring has to be installed on the host system. Please also consult https://gitlab.com/Schmiddiii/flare/-/issues/4 for information.

I will close this now as this has already been discussed upstream.
