### ISSUE TITLE
No way to pair

### ISSUE THREAD

**Issue by firefoxlover** [flathub/de.schmidhuberj.Flare#24]
I dont know if this is related, but I have no setting to pair my device. Libsecret is not found, which may be a problem.

**Comment by Schmiddiii** [comment]
Did you take a look at [this comment](https://gitlab.com/Schmiddiii/flare/-/issues/4#note_1234642176), which should fix the problem. Note that, to my knowledge, there is nothing I can do to fix this as (inside Flatpak) one cannot create the default keyring. Normally, this should be created by the distribution.

**Comment by Schmiddiii** [comment]
I will also close this as there is nothing Flare can do in that case.
